### ISSUE TITLE
Authentication - Sign up screen UI

### ISSUE THREAD

**Issue by suesitran** [suesitran/interactive_diary#16]
# Narrative
As a user of Interactive Diary
I want to sign up to Interactive Diary
So that I can use Interactive Diary with own authentication

# Scenarios
GIVEN I launch the app in anonymous mode
WHEN I tap on Anonymous icon
AND I selected Sign up option
THEN I'll be presented with Sign up screen, with UI below

Sample UI is on iphone12 screen

![Authentication-UI](https://user-images.githubusercontent.com/17781268/184569364-662337a2-bb53-45bf-974a-6346dfcc1d4e.png)

# Technical requirement
These technical requirement are to be implemented in code
- Strings are to be used in localisation

**Comment by kartikey4474** [comment]
I want to work on this issue. please assign it to me.

**Comment by suesitran** [comment]
thanks @kartikey4474, I assigned it to u
