### ISSUE TITLE
App first launch When location permission is denied

### ISSUE THREAD

**Issue by suesitran** [suesitran/interactive_diary#26]
When error happens while loading current location, handle them gracefully

## Narrative
As a diary lover
I want to receive clear indicator what error happens to my location service
So that I can resolve issue and continue using the app

### Location permission is denied
**Scenario 1:**
GIVEN Location permission is denied 
AND Internet connection is available
AND I do not have any location stored in storage
WHEN I launch the app
THEN I'll be presented a dialog to explain why location permission is needed

**Dialog content:**
_Title:_ Location Permission not granted
_Content:_ Location Permission is needed to use this app. Please Allow Interactive Diary to access location in the next dialog.
_Button:_ Allow
_Button:_ Continue

Action on Buttons:
Allow => launch native Location permission request dialog
Continue => Close the dialog

**Scenario 2:**
GIVEN scenario 1
WHEN I tap on 'Continue' button
THEN the map is loaded with default location lat/lng

**Scenario 3:**
GIVEN scenario 1
WHEN I tap on 'Allow' button
THEN native Location permission request dialog is presented to me

**Scenario 4:**
GIVEN scenario 3
WHEN I tap on 'Deny' button 
THEN Location permission dialog is dismissed
AND I'll be presented a dialog to explain why location permission is needed

**Scenario 5:**
GIVEN scenario 3
WHEN I tap on 'Deny, do not ask again'
THEN Location permission dialog is dismissed
THEN I'll be presented a dialog to explain why location permission is needed

**Scenario 6:**
GIVEN scenario 5
WHEN I tap on 'Allow' button
THEN I'll be navigated to native App Setting screen, where I can change location permission for my app.

**Comment by suesitran** [comment]
tesitng testing

**Comment by lqchuong** [comment]
let me take on this task

**Comment by suesitran** [comment]
thanks @lqchuong

**Comment by lqchuong** [comment]
Done, waiting for review

**Comment by suesitran** [comment]
@lqchuong where's the code?

**Comment by suesitran** [comment]
there's still issue with scenario 4 and 5
