### ISSUE TITLE
Tech: Connectivity service

### ISSUE THREAD

**Issue by suesitran** [suesitran/interactive_diary#38]
Tech task:
- create package nartus_connectivity in /packages
- this package will use connectivity_plus package
- it needs to give a stream output, which reports connection status whenever connectivity change

Logic:
- connecting to mobile/wifi/bluetooth/ethernet => online
- no connection => Offline

There’s an edge case when device might be connected to wifi host, but the wifi itself has no internet connection.

This will be covered as part of Storage implementation

**Comment by lqchuong** [comment]
may i take on this task ?
