### ISSUE TITLE
Screenshots in README

### ISSUE THREAD

**Issue by lmk-anz** [suesitran/interactive_diary#72]
Hi there Suesi,

I'd be interested to see some screenshots in your README. The mind maps are great at communicating the core ideas behind your project, but as a Flutter beginner I'd love to see some screenshots without having to download & build the app.

Keep up the good work!

**Comment by suesitran** [comment]
Hi @lmk-anz,

The app is still in progress and we do not have any screenshot ready yet. Thanks for your interest.
